<?php require_once('../start.php')?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Admin Panel | <?php echo $site; ?></title>
<meta name="Description" content="Indo followers aplikasi bikin banyak pengikut"/>
<meta name="Keywords" content="Indo Follower, get more twitter followers, twitter, free followers, buy twitter follower, get more followers on twitter, how to get more twitter followers, pengikut gratis"/>
<link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon" />
<link rel="stylesheet" type="text/css" href="2.css"/>
<meta name="viewport" content="width=460">
</head>
<body>
<center><div class="logo">
    <a href="index.php">
        Admin Panel
    </a>
</div></center></div>
<center>	
<div id="header">
        <div class="header">
        	<ul><center>
<li><a href="./index.php">Home</a></li>
                <li><a href="./Masstweet.php">Mass Tweet</a></li>
                <li><a href="./autospamer.php">Report Spam</a></li>
		<li><a href="./autoblock.php">Block</a></li>
		<li><a href="./autoUblock.php">UnBlock</a></li>
		<li><a href="./clearsessions.php">Logout</a></li>
            </center></ul>
        </div>
    </div>
</center>

<br>
<center><h3>Hallo Homo Selamat datang :)</center>

</body><br/>
</html>